import type { ProjectRegistrationDraft } from "./types";

export const defaultProjectRegistrationDraft: ProjectRegistrationDraft = {
  eventType: "",
  customEventType: "",
  eventName: "",
  organizer: "",
  eventDate: "",
  participationTrack: "",
  awards: [],
  projectName: "",
  summary: "",
  representativeImageName: "",
  teamName: "",
  projectStartedAt: "",
  projectEndedAt: "",
  categories: [],
  problemAreas: [],
  methods: [],
  customTags: [],
  problemDefinition: "",
  targetAudience: "",
  solution: "",
  coreApproach: "",
  differentiation: "",
  validation: "",
  resultLevel: "",
  activityStatus: "",
  approaches: "",
  constraints: "",
  limitations: "",
  endReason: "",
  nextValidationTasks: "",
  assets: [],
  purpose: "",
  pricingMode: "NEGOTIABLE",
  desiredPoints: "",
  recruitmentTitle: "",
  recruitmentRoles: [],
  recruitmentSkills: "",
  recruitmentHeadcount: "",
  recruitmentSchedule: "",
  recruitmentWorkMode: "",
  recruitmentDeadline: "",
  recruitmentApplicationNote: "",
  materialDisclosureConsent: false,
};
